// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WithYou.Web.Data;

namespace WithYou.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WithYou.Web.Data.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.Investigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("ProyectTypeId");

                    b.Property<int?>("RepublicStateId");

                    b.HasKey("Id");

                    b.HasIndex("ProyectTypeId");

                    b.HasIndex("RepublicStateId");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.Leader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("Enrollment");

                    b.Property<string>("FirstName");

                    b.Property<int?>("GenderId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Leaders");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.ProyectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProyectTypes");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.RepublicState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RepublicStates");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.Researcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("Enrollment");

                    b.Property<string>("FirstName");

                    b.Property<int?>("GenderId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Researchers");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.Investigation", b =>
                {
                    b.HasOne("WithYou.Web.Data.Entities.ProyectType")
                        .WithMany("Investigations")
                        .HasForeignKey("ProyectTypeId");

                    b.HasOne("WithYou.Web.Data.Entities.RepublicState")
                        .WithMany("Investigations")
                        .HasForeignKey("RepublicStateId");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.Leader", b =>
                {
                    b.HasOne("WithYou.Web.Data.Entities.Gender", "Gender")
                        .WithMany("Leaders")
                        .HasForeignKey("GenderId");
                });

            modelBuilder.Entity("WithYou.Web.Data.Entities.Researcher", b =>
                {
                    b.HasOne("WithYou.Web.Data.Entities.Gender", "Gender")
                        .WithMany("Researchers")
                        .HasForeignKey("GenderId");
                });
#pragma warning restore 612, 618
        }
    }
}
